firestore:
  users-collection: users
  service-account-key-path: service-account-key-path
#axon:
#  axonserver:
#    servers: 34.68.198.203
logging:
  level:
    web: TRACE
okta:
  oauth2:
    issuer: issuer
    client-id: client-id
    client-secret: client-secret
    token-path: /v1/token
    token-redirect-uri: http://localhost:8080/authorization-code/callback
    authorize-path: /v1/authorize
