firestore:
  users-collection: users
  service-account-key-path: service-account-key-path
bigquery:
  dataset: dataflow
  table: dataflow
spring:
  cloud:
    gcp:
      project-id: gcp-trainings-272313bigquery
  profiles:
    active: default
axon:
  axonserver:
    servers: 35.198.114.17
logging:
  level:
    web: TRACE
okta:
  oauth2:
    issuer: https://dev-795162.okta.com/oauth2/default
    client-id:
    client-secret:
    token-path: /v1/token
    token-redirect-uri: https://reactive-rest-api-dot-gcp-trainings-272313.appspot.com/authorization-code/callback
    authorize-path: /v1/authorize
