FROM openjdk:11
WORKDIR /usr/src/firestore-connector
COPY firestore-connector-1.0.jar /usr/src/firestore-connector/firestore-connector-1.0.jar
ENTRYPOINT ["java", "-jar", "firestore-connector-1.0.jar"]
