spring:
  cloud:
    gcp:
      project-id: my-project-oril
      pub-sub:
        csv-processor-subscription-name: projects/gcp-trainings-272313/subscriptions/gcp-csv-files-bucket-notifications-topic-csv-processor-subscription
        dataflow-json-processing-topic-name: projects/gcp-trainings-272313/topics/dataflow-json-processing-topic
logging:
  level:
    com:
      epam:
        gcp: DEBUG